package com.agentplatform.gateway.vector;

import com.agentplatform.gateway.rag.chunking.ChunkingConfig;
import io.milvus.client.MilvusServiceClient;
import io.milvus.param.*;
import io.milvus.param.dml.InsertParam;
import io.milvus.param.dml.SearchParam;
import io.milvus.param.index.*;
import io.milvus.response.SearchResultsWrapper;
import lombok.extern.slf4j.Slf4j;
import org.springframework.ai.document.Document;
import org.springframework.ai.embedding.EmbeddingModel;
import org.springframework.ai.vectorstore.SearchRequest;
import org.springframework.ai.vectorstore.Filter;
import org.springframework.ai.vectorstore.VectorStore;
import org.springframework.ai.vectorstore.milvus.MilvusVectorStore;
import org.springframework.util.Assert;

import java.util.*;
import java.util.stream.Collectors;

/**
 * 支持稀疏向量的 Milvus VectorStore 实现
 * 扩展 MilvusVectorStore 以支持稀疏向量插入和混合搜索
 */
@Slf4j
public class SparseMilvusVectorStore implements VectorStore {

@SuppressWarnings("unused")
    private final MilvusServiceClient milvusClient;
    @SuppressWarnings("unused")
    private final EmbeddingModel embeddingModel;
    private final String collectionName;
    private final String databaseName;
    private final ChunkingConfig chunkingConfig;

    // 基础的 MilvusVectorStore 用于稠密向量操作
    private final MilvusVectorStore denseVectorStore;

    public SparseMilvusVectorStore(MilvusServiceClient milvusClient,
                                   EmbeddingModel embeddingModel,
                                   String collectionName,
                                   String databaseName,
                                   ChunkingConfig chunkingConfig) {
        Assert.notNull(milvusClient, "MilvusServiceClient must not be null");
        Assert.notNull(embeddingModel, "EmbeddingModel must not be null");
        Assert.notNull(collectionName, "CollectionName must not be null");

        this.milvusClient = milvusClient;
        this.embeddingModel = embeddingModel;
        this.collectionName = collectionName;
        this.databaseName = databaseName != null ? databaseName : "default";
        this.chunkingConfig = chunkingConfig;

        // 创建基础的 MilvusVectorStore 用于稠密向量操作
        this.denseVectorStore = MilvusVectorStore.builder(milvusClient, embeddingModel)
            .collectionName(collectionName)
            .databaseName(this.databaseName)
            .build();

        log.info("Created SparseMilvusVectorStore for collection '{}' with sparse support enabled: {}",
            collectionName, chunkingConfig != null && chunkingConfig.isEnableSparseVector());
    }

    @Override
    public void add(List<Document> documents) {
        if (chunkingConfig != null && chunkingConfig.isEnableSparseVector()) {
            // 启用稀疏向量时，使用自定义插入逻辑
            addWithSparseVectors(documents);
        } else {
            // 仅使用稠密向量
            denseVectorStore.add(documents);
        }
    }

    @Override
    public Optional<Boolean> delete(Filter.Expression expression) {
        return denseVectorStore.delete(expression);
    }

    @Override
    public void delete(List<String> idList) {
        denseVectorStore.delete(idList);
    }

    @Override
    public List<Document> similaritySearch(SearchRequest request) {
        if (chunkingConfig != null && chunkingConfig.isEnableSparseVector()) {
            // 启用稀疏向量时，使用混合搜索
            return hybridSimilaritySearch(request);
        } else {
            // 仅使用稠密向量搜索
            return denseVectorStore.similaritySearch(request);
        }
    }

    /**
     * 使用稀疏向量插入文档
     */
    private void addWithSparseVectors(List<Document> documents) {
        try {
            // 首先使用基础的 MilvusVectorStore 来插入稠密向量和基础字段
            denseVectorStore.add(documents);

            // 对于稀疏向量，我们需要使用 Milvus 的原生 API 来插入稀疏向量数据
            // 由于当前 Milvus Java 客户端对稀疏向量的支持有限，我们暂时记录日志
            // 在实际生产环境中，这里应该使用 Milvus 的稀疏向量 API 或 BM25 analyzer
            
            boolean hasSparseVectors = documents.stream()
                .anyMatch(doc -> {
                    Map<String, Object> metadata = doc.getMetadata();
                    return metadata != null && metadata.containsKey("enable_sparse_vector");
                });

            if (hasSparseVectors) {
                log.info("Documents marked for sparse vector processing. Sparse vectors will be generated by Milvus analyzer/BM25.");
                
                // 在实际实现中，这里应该：
                // 1. 调用 Milvus 的稀疏向量插入 API
                // 2. 或者使用 Milvus 的全文检索功能
                // 3. 确保 sparse_vector 和 text 字段被正确填充
                
                // 暂时只记录日志，因为稀疏向量通常由 Milvus 内部生成
                documents.forEach(doc -> {
                    Map<String, Object> metadata = doc.getMetadata();
                    if (metadata != null && metadata.containsKey("enable_sparse_vector")) {
                        log.debug("Document {} marked for sparse processing with analyzer: {}", 
                            doc.getId(), metadata.get("sparse_analyzer"));
                    }
                });
            }

        } catch (Exception e) {
            log.error("Failed to insert documents with sparse vectors to collection '{}'", collectionName, e);
            throw new RuntimeException("Failed to insert documents with sparse vectors", e);
        }
    }

    /**
     * 执行混合相似度搜索（稠密 + 稀疏向量）
     */
    private List<Document> hybridSimilaritySearch(SearchRequest request) {
        try {
            log.info("Performing hybrid similarity search with dense + sparse vectors");
            
            // 由于当前 Milvus Java 客户端对混合搜索的支持有限，
            // 我们先实现一个简化版本：稠密向量搜索 + 日志记录
            // 在实际生产环境中，这里应该使用 Milvus 的 Hybrid Search API
            
            // 1. 执行稠密向量搜索
            List<Document> denseResults = denseVectorStore.similaritySearch(request);
            log.debug("Dense vector search returned {} results", denseResults.size());
            
            // 2. 在实际实现中，这里应该执行稀疏向量搜索
            // List<Document> sparseResults = performSparseSearch(request);
            // log.debug("Sparse vector search returned {} results", sparseResults.size());
            
            // 3. 融合稠密和稀疏搜索结果
            // return mergeSearchResults(denseResults, sparseResults, request);
            
            // 暂时返回稠密搜索结果，但添加混合搜索的元数据
            return denseResults.stream()
                .map(doc -> {
                    // 创建新的文档副本，添加混合搜索的元数据
                    Map<String, Object> originalMetadata = doc.getMetadata();
                    Map<String, Object> newMetadata = originalMetadata != null ? 
                        new HashMap<>(originalMetadata) : new HashMap<>();
                    
                    newMetadata.put("search_mode", "hybrid");
                    newMetadata.put("dense_score", doc.getScore());
                    newMetadata.put("sparse_score", null); // 暂时为空
                    newMetadata.put("hybrid_score", doc.getScore()); // 暂时使用稠密得分
                    
                    return new Document(doc.getId(), doc.getText(), newMetadata);
                })
                .collect(Collectors.toList());

        } catch (Exception e) {
            log.error("Failed to perform hybrid similarity search", e);
            return Collections.emptyList();
        }
    }
}
